Update Dockerfile
Without libavif assembly crashes with error
ERROR: unable to select packages:
  so:libavif.so.13 (no such package):
    required by: php81-gd-8.1.2-r2[so:libavif.so.13]